spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/realestate?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 4869
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # Spring boot 2.6버전 이후부터 발생하는 Swagger3.0.0 충돌 문제 해결하기 위한 설정
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: mapper/*xml


